POST https://localhost:7107/auth/login
Content-Type: application/json

{ "Username" : "axeku", "Password" : "1234" }

###

POST https://localhost:7107/auth/login
Content-Type: application/json

{ "Username" : "Krollo", "Password" : "password" }

###

POST https://localhost:7107/auth/login
Content-Type: application/json

{ "Username" : "Krollo", "Password" : "passord" }

###

POST https://localhost:7107/auth/login
Content-Type: application/json

{ "Username" : "axeku", "Password" : "234" }


###
POST https://localhost:7107/Users/CreateUser
Content-Type: application/json

{"userName": "axeku",
  "passWord": "234",
  "email": "alecsen@gmail.com",
  "domain": "gmail.com",
  "name": "Alexander",
  "role": "god",
  "age": 24,
  "securityLevel": 5}